development:
  adapter: postgresql
  encoding: unicode
  database: RefineryTeacherPage_development
  pool: 5
  timeout: 5000
  username: luigolas
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: RefineryTeacherPage_test
  pool: 5
  timeout: 5000
  username: luigolas
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: RefineryTeacherPage_production
  pool: 5
  timeout: 5000
  username: luigolas
  password: